# Generated by Django 5.2.8 on 2026-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='name',
            field=models.CharField(choices=[('Gemini', 'Gemini'), ('OpenRouter', 'OpenRouter'), ('Groq', 'Groq')], max_length=50, unique=True),
        ),
    ]
