# Generated by Django 5.2.8 on 2026-05-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chatmessage_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='parent',
        ),
    ]
