# Generated by Django 5.2.8 on 2026-06-14 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_llmprovider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
