# Generated by Django 5.2.8 on 2026-06-14 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chatsession_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
