# Generated by Django 5.2.8 on 2026-05-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_chatmessage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
